#!/usr/bin/env node
'use strict';

/*
Display synonym(s) of a word
 */

var getRelatedWords = require('./helpers/get_related_words.js');
var word = process.argv[2];

// Callback to process and display results
var fnDisplayResults = function(error, response, body) {
  var dataObjArr = JSON.parse(body);
  console.info('Word:', word);
  console.info('Synonym(s)');

  dataObjArr.forEach(function(dataObj) {
    var synonyms = dataObj.words;
    synonyms.forEach(function(synonym, index) {
      console.info(++index + '.', synonym);
    });
  });
};

// Display an error message if the required argument is missing
if (!word)
  console.error('Required <word> argument missing!');
else
  getRelatedWords(word, false, 'synonym', 3, fnDisplayResults);
