#!/usr/bin/env node
'use strict';

/*
Display definition(s) of a word
 */

var getDefinitions = require('./helpers/get_definitions.js');
var word = process.argv[2];

// Callback to process and display results
var fnDisplayResults = function(error, response, body) {
  var dataObjArr = JSON.parse(body);
  console.info('Word:', word);
  console.info('Definition(s)');
  dataObjArr.forEach(function(dataObj, index) {
    console.info(++index + '.', dataObj.text);
  });
};

// Display an error message if the required argument is missing
if (!word)
  console.error('Required <word> argument missing!');
else
  getDefinitions(word, 3, 'noun', false, 'wordnet', false, false, fnDisplayResults);
