#!/usr/bin/env node
'use strict';

var getRelatedWords = require('./helpers/get_related_words.js');

/*
Display synonyms of a word
 */

var word;

if (process.argv[2]) {
  word = process.argv[2];
}

console.log('Displaying synonyms of the word: ', word);

getRelatedWords(word, false, 'synonym', 3);
